name: Practica GitHub Actions

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      platform: aws
      region: us-east-1
      PASS: ${{ secrets.password }}

    steps:
      - name: Hola Mundo inicial
        run: echo "Hola Mundo"

      - name: Auditoria de variables
        run: |
          echo "Plataforma: ${{ env.platform }}"
          echo "Version: ${{ vars.project_version }}"

      - name: Ejecucion condicional (Solo AWS)
        if: env.platform == 'aws'
        run: echo "Este paso se ejecuta porque la plataforma es AWS"

      - name: Validacion de secretos
        run: echo "Probando ocultamiento de secreto... El pass es ${{ env.PASS }}"

      - name: Debug del payload JSON
        run: echo "${{ toJSON(github.event) }}"